### ISSUE TITLE
Extra Features - Speed / ETA

### ISSUE THREAD

**Issue by blandyuk** [cyclone-github/metamask_decryptor#1]
Hi cyclone,

Just some wish list features:

1. Wordlist progress in % along with ETA.
2. Speed via [s]tatus key of every few seconds, (maybe configure via command-line parameter)?
3. Multithreaded support.

Thanks, Blandy.

**Comment by cyclone-github** [comment]
Hey Blandy,

Great suggestions. Multithreading support is already on the to-do list.
https://github.com/cyclone-github/metamask_decryptor/blob/6c9046d4a7e59204ab4965db98b05a041dfe466b/metamask_decryptor.go#L32

**Comment by cyclone-github** [comment]
Added multithreading and stats. Will look into ETA / progress as time allows.
https://github.com/cyclone-github/metamask_decryptor/commit/f552cd4155ca29046ff6d304504ec3d0173f2121
